name: flower_blossom
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.3.7
  dartz: ^0.10.1
  equatable: ^2.0.5
  uuid: ^3.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  image_picker: ^1.0.7
  path: ^1.9.0
  dio: ^5.4.1
  dio_smart_retry: ^7.0.1
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^7.0.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  jwt_decoder: ^2.0.1
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # ðŸ§ª TESTING DEPENDENCIES
  mockito: ^5.4.4                    # For mocking objects in unit tests
  build_runner: ^2.4.6               # Required to generate mock classes
  hive_generator: ^2.0.1             # For Hive adapters generation
  
  # Code quality
  analyzer: ^6.4.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/